#!/bin/sh

# Saumon i3blocks scripts : brightness (display current screen brightness in % and change on scroll)


case $BLOCK_BUTTON in
	4) light -A 2;; # scroll up : increase brightness by 5%
	5) light -U 2;; # scroll down : decrease brightness by 5%
esac


echo -n "  "
light | xargs printf %.0f
echo -n "<span font_size=\"small\">%</span>"
