#!/bin/sh
#
# Saumon i3blocks scripts
# brightness (display current screen brightness in % and change on scroll)
#

case $BLOCK_BUTTON in
  4) # scroll up : increase brightness by 1%
    light -A 1
    ;;
  5) # scroll down : decrease brightness by 1%
    light -U 1
    ;;
esac

printf "<span fallback='true'>  </span>%.0f<span font_size='small'>%%</span>" "$(light)"
