#!/bin/sh
#
# Saumon i3blocks scripts
# brightness (display current screen brightness in % and change on scroll)
#

command="brightnessctl -m"

case $BLOCK_BUTTON in
  3) # right click: toggle min/full brightness
    rounded=$($command | cut -d ',' -f4 |  tr -d '%')
    if [ "$rounded" -ge 50 ]; then
      command="sudo brightnessctl -m set 100%"
    else
      command="sudo brightnessctl -m set 1"
    fi
    ;;
  4) # scroll up: increase brightness by 2%
    command="sudo brightnessctl -m set -m +2%"
    ;;
  5) # scroll down: decrease brightness by 2%
    command="sudo brightnessctl -m set -m 2%-"
    ;;
esac

current=$($command | cut -d ',' -f4 |  tr -d '%')

if [ -z "$current" ]; then
  printf " <span fallback='true'>  </span>?? \n"
  exit 0
fi

printf " <span fallback='true'>  </span>$current<span font_size='small'>%%</span> \n"
