#!/bin/sh
#
# Saumon i3blocks scripts
# date (display date and calendar popup on click)
#

case $BLOCK_BUTTON in
  1) gsimplecal ;;
  2) date +%s | tr -d '\n' | xclip -i -selection clipboard ;;
  3) date +%s | tr -d '\n' | xclip -i -selection clipboard ;;
esac

printf " "
date '+%a  %Y-%m-%d '
