#!/bin/sh

# Saumon i3blocks scripts : INTERNET (wired/wifi network info with external ip on middle click)


case $BLOCK_BUTTON in
	2) IP=$(curl -s "ifconfig.me/ip" | tr -d '\n'); notify-send "External IP address" $IP; echo -n $IP | xclip -i -selection clipboard ;;
esac

ifaceWIFI=wlp2s0
ifaceETH=enp0s31f6

statusWIFI=$(cat -- "$(readlink -e -- /sys/class/net/$ifaceWIFI/operstate)")
statusETH=$(cat -- "$(readlink -e -- /sys/class/net/$ifaceETH/operstate)")

if [ "$statusETH" = "up" ]; then
	echo -n '<span color="#19ef5d"><b></b>  '
	ip addr show enp0s31f6 | awk '/inet / {print $2}' | cut -d '/' -f1 | tr -d '\n'
	echo -n '</span>'
elif [ "$statusWIFI" = "up" ]; then
	IPaddr=$(ip addr show "$ifaceWIFI" | awk '/inet / {print $2}' | cut -d '/' -f1 | tr -d '\n')
	NetName=$(iwgetid -r | tr -d '\n')
	if [ "$IPaddr" = "" ]; then
		echo -n '<span color="#fa8026">  (no IP)</span>'
	else
		echo -n "<span color=\"#19ef5d\">  $IPaddr</span> <span font_size=\"small\">on</span> $NetName"
	fi
else
	echo -n '<span color="#fa3826" font-weight="bold">INTERNET ?</span>'
fi
