#!/bin/sh

# Saumon i3blocks scripts : load (1 min load with colors)


load=$(cat /proc/loadavg | cut -d ' ' -f1 | tr -d '\n')
loadC=$(echo "$load * 100" | bc -l | xargs printf "%.0f")

if [ $loadC -ge 400 ]; then
	color="#fa3826"
elif [ $loadC -ge 300 ]; then
	color="#fa8026"
else
	color="#cccccc"
fi

echo -n "<span color='$color'><b>  </b>$load</span>"
