#!/bin/sh
#
# Saumon i3blocks scripts : load
# (1 min load with colors)
#

load=$(cut -d ' ' -f1 /proc/loadavg | tr -d '\n')
loadC=$(echo "$load * 100" | bc -l | xargs printf "%.0f")

if [ "$loadC" -ge 400 ]; then
  color="#f44336"
elif [ "$loadC" -ge 300 ]; then
  color="#ff9800"
else
  color="#cccccc"
fi

printf "<span color='%s'>  %s</span>" "$color" "$load"
