#!/bin/sh

act() {
    status=$(mpc "$1")
    playing=$(echo "$status" | grep "playing")
    paused=$(echo "$status" | grep "paused")
    repeat=$(echo "$status" | grep "repeat: on")
    if [[ $playing ]]; then
        echo -n '<span color="#19ef5d">  ' # playing icon
        echo -n "$status" | head -n1 | tr -d '\n'
    elif [[ $paused ]]; then
        echo -n '<span color="#fa8026">  ' # paused icon
        echo -n "$status" | head -n1 | tr -d '\n'
    else
        echo -n '<span color="#999">  ' # music icon
        echo -n "Stopped"
    fi
    echo -n "</span>"
}

case $BLOCK_BUTTON in
    3) act toggle ;;  # right click, pause/unpause
    4) act prev ;;  # scroll up, previous
    5) act next ;;  # scroll down, next
    *) act status ;;
esac
