#!/bin/sh

lockfile="/tmp/saumon-music-instance.lock"
instance="`cat $lockfile`"

if [[ $BLOCK_BUTTON -eq 2 ]]; then

    if [[ "$instance" = "mpd" ]]; then
        mpc pause-if-playing > /dev/null 2>&1
        echo "spotify" > $lockfile
        instance="spotify"
    elif [[ "$instance" = "spotify" ]]; then
        playerctl --player=spotify pause > /dev/null 2>&1
        echo "none" > $lockfile
        instance="none"
    else
        echo "mpd" > $lockfile
        instance="mpd"
    fi

fi

if [[ "$instance" = "mpd" ]]; then

    act() {
        status=$(mpc "$1")
        playing=$(echo "$status" | grep "playing")
        paused=$(echo "$status" | grep "paused")
        repeat=$(echo "$status" | grep "repeat: on")
        if [[ $playing ]]; then
            echo -n '<span color="#8BC34A">  ' # playing icon
            echo -n "$status" | head -n1 | tr -d '\n' | sed -r 's/&/&amp;/g'
        elif [[ $paused ]]; then
            echo -n '<span color="#EF6C00">  ' # paused icon
            echo -n "$status" | head -n1 | tr -d '\n' | sed -r 's/&/&amp;/g'
        else
            echo -n '<span color="#999">  ' # music icon
            echo -n "Stopped"
        fi
        echo -n " </span>"
    }

    case $BLOCK_BUTTON in
        3) act toggle ;;  # right click, pause/unpause
        4) act prev ;;  # scroll up, previous
        5) act next ;;  # scroll down, next
        *) act status ;;
    esac

elif [[ "$instance" = "spotify" ]]; then

    case $BLOCK_BUTTON in
        3) $(playerctl --player=spotify play-pause && pkill -RTMIN+13 i3blocks) ;;  # right click, pause/unpause
        4) $(playerctl --player=spotify previous && pkill -RTMIN+13 i3blocks && sleep 0.1 && pkill -RTMIN+13 i3blocks) ;;  # scroll up, previous
        5) $(playerctl --player=spotify next && pkill -RTMIN+13 i3blocks && sleep 0.1 && pkill -RTMIN+13 i3blocks) ;;  # scroll down, next
    esac


    STATUS=$(playerctl --player=spotify status 2> /dev/null)
    DATA=$(playerctl --player=spotify metadata --format "{{ artist }} - {{ title }}" 2> /dev/null)

    if [[ "${STATUS}" = "Playing" ]]; then
        echo -n "<span color='#8BC34A'><span fallback='true'> </span> "
        echo -n "${DATA}" | sed -r 's/&/&amp;/g'
    elif [[ "${STATUS}" = "Paused" ]]; then
        echo -n "<span color='#EF6C00'><span fallback='true'> </span> "
        echo -n "${DATA}" | sed -r 's/&/&amp;/g'
    else
        echo -n "<span fallback='true'>                            </span><span color='#999'><span fallback='true'> Stopped </span>"
    fi

    echo -n "</span>"

else

    echo -n "<span fallback='true'>                               </span><span color='#999999'><span fallback='true'>  </span>Idle</span>"

fi
