#!/bin/sh
#
# Saumon i3blocks scripts
# updates (display number of pending Arch updates)
#

number=$(checkupdates | wc -l)

if [ "$number" -gt 5 ]; then
  printf "<span color='#ff9800'>  %s</span>\n" "$number"
else
  printf "<span>  %s</span>\n" "$number"
fi
