#!/bin/sh

# Saumon i3blocks scripts : updates (display number of pending Arch updates)

number=$(checkupdates | wc -l)

if [ $number -gt 5 ]; then
    spanargs=" color='#ff9800'"
else
    spanargs=""
fi

echo -n "<span$spanargs>  $number</span>"
