#!/bin/sh

# Saumon i3blocks scripts : volume (display main volume, mute on right click and change on scroll)


case $BLOCK_BUTTON in
	3) pactl set-sink-mute @DEFAULT_SINK@ toggle;; # right click : toggle mute
	4) pactl set-sink-volume @DEFAULT_SINK@ +2% ;; # scroll up : increase vol by 2%
	5) pactl set-sink-volume @DEFAULT_SINK@ -2%;; # scroll down : decrease vol by 2%
esac


sinks=$(pactl list sinks)
isbluetooth=$(echo "$sinks" | grep bluez)
ismuted=$(echo "$sinks" | grep "Mute: " | tail -1 | awk '{print $2}')
volume=$(echo "$sinks" | grep "Volume: " | tail -2 | head -1 | awk '{print $5}' | tr -d '%')

if [[ ! -z $isbluetooth ]]; then
	color="#2896ff"
	if [[ "$ismuted" == "yes" ]]; then
		color="#997CC5"
	fi
elif [[ "$ismuted" == "yes" ]]; then
	color="#fa8026"
else
	color="#dddddd"
fi
echo -n "<span color='$color'>"
if [[ ! -z "$isbluetooth" ]]; then
	echo -n "  "
fi
if [[ "$ismuted" == "yes" ]]; then
	echo -n "  (muted) $volume"
elif [ $volume -ge 40 ]; then
	echo -n "  $volume"
else
	echo -n "  $volume"
fi
echo -n "<span font_size=\"small\">%</span></span>"
