#!/bin/bash

set -e

dest_dir_root="/tmp/spectrograms"

echo "$NEMO_SCRIPT_SELECTED_FILE_PATHS" | while read -r filename; do
  if [ -z "$filename" ]; then
    continue
  fi
  basename=$(basename "$filename")
  if [ -d "$filename" ]; then
    notify-send -u low -t 20000 "Generating spectrograms" "Opening target directory for $filename"
    dest_dir="$dest_dir_root/$basename"
    mkdir -p "$dest_dir"
    xdg-open "$dest_dir"
    pushd "$filename" || continue
    for f in *.flac; do
      sox "$f" -n spectrogram -o "$dest_dir/${f%.flac}.png"
    done
    notify-send -t 2000 "Spectrograms generated" "All spectrograms generated for $filename"
  else
    mkdir -p "$dest_dir_root"
    id=$(md5sum "$filename" | awk '{ print $1 }')
    dest_file="$dest_dir_root/$id.png"
    sox "$filename" -n spectrogram -o "$dest_file" && xdg-open "$dest_file"
    rm "$dest_file"
  fi
done
