#!/bin/sh

# Saumon i3blocks scripts : battery (battery percentage and state)


battInfo=$(acpi)
battStatus=$(echo $battInfo | awk '/ / {print $3}' | tr -d ',')
battCapacity=$(echo $battInfo | awk '/ / {print $4}' | tr -d '%,\n')
battRemain=$(echo $battInfo | awk '/ / {print $5}' | sed 's/...$//' | tr -d '\n')

if [ \( "$battStatus" = "Charging" \) -o \( "$battRemain" = "discharg" \) ]; then
	if [ $battCapacity -lt "90" ]; then
		color="#19ef5d"
	else
		color="#cccccc"
	fi
	echo -n "<span color='$color'>  $battCapacity%</span>"
else
	if [ $battCapacity -lt "20" ]; then
		color="#fa3826"
	elif [ $battCapacity -lt "50" ]; then
		color="#fa8026"
	else
		color="#cccccc"
	fi
	echo -n "<span color='$color'>  $battCapacity% ($battRemain)</span>"
fi
