#!/bin/sh

# Saumon i3blocks scripts : brightness (display current screen brightness in % and change on scroll)


case $BLOCK_BUTTON in
	4) light -A 5;; # scroll up : increase brightness by 5%
	5) light -U 5;; # scroll down : decrease brightness by 5%
esac


echo -n " "
light | xargs printf %.0f
echo -n "%"
