#!/bin/sh

# Saumon i3blocks scripts : disk (free space in GB and % of / and /data)


echo -n "  "

df -h -P -l / | tail -n1 | sed -e 's/\s\+/\t/g' | cut -f4-5 | sed -e 's/\(.*\)\s\(.*\)/\1 (\2)/' | tr -d '\n'

echo -n "      "

df -h -P -l /home | tail -n1 | sed -e 's/\s\+/\t/g' | cut -f4-5 | sed -e 's/\(.*\)\s\(.*\)/\1 (\2)/' | tr -d '\n'
