# Configuration file for libinput-gestures.

gesture swipe left  swaymsg workspace next
gesture swipe right swaymsg workspace prev

# key list is in /usr/include/linux/input-event-codes.h

# KEY_BACK
gesture swipe up    ydotool key 158:1 158:0
# KEY_FORWARD
gesture swipe down  ydotool key 159:1 159:0
