#!/bin/bash

files=()
while read -r filename; do
  if [ -n "$filename" ]; then
    files+=("$filename")
  fi
done < <(printf "%s" "$NEMO_SCRIPT_SELECTED_FILE_PATHS")

for filename in "${files[@]}"; do
  basename=$(basename "$filename")
  if [ -d "$filename" ]; then
    id=$(dunstify --printid --timeout 30000 -u low "Transcoding MP3 V0" "Trancoding $basename to MP3 VBR V0")
    pushd "$filename" || continue
    if "$HOME/scripts/music/transcode-flac-mp3-v0.sh"; then
      dunstify --replace="$id" "Transcoding successful" "$basename"
    else
      dunstify --replace="$id" -u critical "Transcoding failed" "$basename"
    fi
  else
    notify-send -u critical "Transcoding failed" "Transcoding files through Nemo is not yet supported."
  fi
done
