# vim:ft=kitty

## name: Saumon

#: The basic colors

foreground #eee
background #000

selection_foreground #000000
selection_background #e0caf5



#: Cursor colors

cursor #fff


#: Tab bar colors

tab_bar_background #010409
active_tab_foreground #f0f3f6
active_tab_background #0a0c10
inactive_tab_foreground #f0f3f6
inactive_tab_background #010409


#: The basic 16 colors

#: black
color0 #3A424A
color8 #65676B

#: red
color1 #FF4442
color9 #FF8F8C

#: green
color2 #26cd4d
color10 #4ae168

#: yellow
color3 #f0b72f
color11 #f7c843

#: blue
color4 #2490FF
color12 #54AFFF

#: magenta
color5 #BD59FF
color13 #C994FF

#: cyan
color6 #39c5cf
color14 #56d4dd

#: white
color7 #E8E8E8
color15 #ffffff
