#
# Saumon ZSH dotfiles
# zprofile: sourced at login
#

source /etc/zsh/zprofile

source "$ZDOTDIR/env.zsh"

# Autostart graphical interface upon login on TTY1
if [ -z "$WAYLAND_DISPLAY" ] && [ "$XDG_VTNR" -eq 1 ]; then
  exec ~/scripts/sway-user-service.sh
fi
