#
# Saumon ZSH dotfiles
# zshrc: main file for interactive shells
#

# Custom completions path
# (must be sourced before prezto as prezto runs compinit)
fpath=("$ZDOTDIR/completions" $fpath)

# prezto, a configuration framework for Zsh
source "$HOME/.zsh/prezto/init.zsh"

# load custom dotfiles
for file in "$HOME/.zsh/"*.zsh; do
  source "${file}"
done

ulimit -c 0

# fg when pressing Ctrl+Z
function fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    if [[ $(jobs | wc -l) -gt 0 ]]; then
      BUFFER='fg'
      zle accept-line
    fi
  else
    zle push-input
    zle clear-screen
  fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z

# Do not save commands beginning with space
setopt HIST_IGNORE_SPACE

# cd to directory when just typing its name
# useful for fzf
setopt auto_cd

# https://github.com/skywind3000/z.lua
if [ -f "/usr/share/z.lua/z.lua" ]; then
  eval "$(lua /usr/share/z.lua/z.lua --init zsh)"
fi

if [ -f "/usr/share/doc/fzf/examples/key-bindings.zsh" ]; then
  source "/usr/share/doc/fzf/examples/key-bindings.zsh"
fi
