#
# Saumon ZSH dotfiles
# zshrc
#

# prezto, a configuration framework for Zsh
source "$HOME/.zsh/prezto/init.zsh"

# load custom dotfiles
for file in "$HOME/.zsh/"*.zsh; do
  source "${file}"
done

ulimit -c 0

# fg when pressing Ctrl+Z
function fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    if [[ $(jobs | wc -l) -gt 0 ]]; then
      BUFFER='fg'
      zle accept-line
    fi
  else
    zle push-input
    zle clear-screen
  fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z

# lazy load fuck because it takes >100ms to load
function fuck() {
  if (( $+commands[thefuck] )); then
    eval $(thefuck --alias)
    fuck $@
  else
    >&2 echo "zobsh: fuck."
    return 127
  fi
}

if (( $+commands[kubectl] )); then
  source <(kubectl completion zsh)
fi

export NVM_DIR="$HOME/.config"
[ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && source "$NVM_DIR/bash_completion"

# fzf, command-line fuzzy finder
if [[ -f "/usr/share/fzf/key-bindings.zsh" ]]; then
  source "/usr/share/fzf/key-bindings.zsh"
fi
